### ISSUE TITLE
Poor search results

### ISSUE THREAD

**Issue by kwarkster** [Code4HR/open-health-inspection-app#123]
-searching for "atlee high school" does not return any results, when there is a result for "atlee high school cafeteria"

-searching some of the most popular restaurants in Carytown don't return results- that doesn't seem right.

**Comment by qwo** [comment]
hi @kwarkster could you list some of these restaurants that are popular and can't be found?

We can do some direct database queries to find out if they're there or theres some weird craziness happening. We can urbanspoon/yelp them to see how popular they are :) or directly check if they have histories.

It would be hilarious for us to uncover some restaurants that have been here for decades but not being inspected because someone lost the file and nobody complained 

cc @ttavenner

**Comment by kwarkster** [comment]
Hey @stanzheng & @ttavenner  - Here are some popular restaurants in the Fan/Carytown/Shockoe Bottom areas- I really hope they've been inspected! 

-Weezie's Kitchen
-Juleps
-Don't Look Back
-Comfort 
-Heritage
-Galaxy Diner
-8 1/2
-Stella's
-Mezzanine
-Accacia

**Comment by wbprice** [comment]
@kwarkster we recently fixed an issue where a lot of restaurants weren't being added to the database correctly.  I tried a couple of these a moment ago and was able to find them.

**Comment by wbprice** [comment]
![screen shot 2014-07-18 at 12 57 20 pm](https://cloud.githubusercontent.com/assets/2590422/3629140/9cb26646-0e9c-11e4-9052-6cefbec2e83b.png)

**Comment by kwarkster** [comment]
Nice! Yep- most of the big ones are showing up now.  Still can't see Juleps though.

**Comment by wbprice** [comment]
Is this one at the right address? http://openhealthinspection.com/#/vendor/53618ced05c6a22dc7b75dc4

**Comment by kwarkster** [comment]
Yeah- on google maps it's listed at 1719 E Franklin.  I guess this goes back to being a little more generous with search criteria.  I get a hit with "Julep's" but not with "Juleps."  I think we need two new features- one that explicitly indicates when your search criteria return no results, and maybe another that suggests a different spelling if your search criteria are just a little off of the correct spelling/name of the restaurant you're looking for.

**Comment by wbprice** [comment]
Agreed.  Error handling and improving search are going to be prioritized.

**Comment by ttavenner** [comment]
We might consider implementing a soundex search. I could generate soundex strings for vendor names and store them in the DB. That might be more useful than a basic regex search (what I'm doing now) and would be able to handle slight differences like apostrophes.

On the address front I have considered storing the SmartyStreets corrected address in the DB. Often the addresses in Healthspace are less correct due to being hand entered without any standardization. I just need to decide how to handle that with the scraper.

**Comment by wbprice** [comment]
would it be easier to search by a version of the restaurant name without special characters (ie julep's --> juleps) and then remove special characters from the search string in the front end before making a call to the API?

**Comment by ttavenner** [comment]
Not necessarily. The name of the restaurant in the database is 'Julep's' with an apostrophe. That is why it didn't come up when searching for 'Juleps'. So to simplify searching we would need to create a second field with all special characters removed. This is also the case for names like 'Caf&eacute;'. In terms of lift that isn't much different than creating a soundex field. I could probably handle it all server side and just replace the current regex search with a search against the soundex. It would require some testing.

**Comment by wbprice** [comment]
@ttavenner I'll defer to your judgement, especially where I don't have to do anything.

**Comment by ttavenner** [comment]
Oh, I'll make sure it requires massive front-end conversion.
