### ISSUE TITLE
Do we need an open source license for this?

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#156]
I don't have any specific experience navigating the various public licenses out there, and not sure if we need to use GPLv3, MIT, WTFPL or what have you.

**Comment by jalbertbowden** [comment]
lol as much as i love wtfpl, i wouldn't use it here....not sure about the other two.
you could always use cc and release it to public domain....

**Comment by ttavenner** [comment]
Yes, giving it some kind of license is a good idea. It lets you dictate the terms of how the code is used. A Creative Commons attribution or non-commercial license would be fine (depending on whether you care about commercial vs. non-commercial use of your code). A GPL license is probably fine as well. The MIT license is useless except as a CYA measure (because of the 'as is' clause.

**Comment by ghost** [comment]
Let me count the code length.  If you have under 300 sloc, I'd say Apache 2.0, otherwise GPLv3.  For the API and scraper, I'd say Affero GPLv3.  My suggestions.

EDIT: Yeah, _easily_ GPLv3.  You should include the header in each HTML/CSS/JS file and make a license web labels page for the dependencies and any minified code.

**Comment by wbprice** [comment]
In that case, unless there are any objections, 1.1 is going out with a GPL v3 license.

**Comment by wbprice** [comment]
Addressed in #165 by @ryayak1460
