### ISSUE TITLE
Implement scoring system

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#167]
Restaurant scores are now in the API!
-Add ability to sort by score and distance (cleanest restaurants near me)
-Add score to restaurants in listview
-Add score to restaurant detail page (score for individual inspections)

**Comment by ttavenner** [comment]
Here is a short and (hopefully) user friendly description of the methodology:

First the fine print:
This scoring system was designed by volunteers at Code for Hampton Roads. It was not provided by the Virginia Department of Health and should not be considered official. These scores are for informational purposes only.

Now the nitty gritty:
Each inspection contains a score based on the number of violations found during that inspection. An inspection starts with a maximum score of 100. For each violation found points are deducted or added based on the following criteria:
- 2 points minimum for the violation
- an additional 1.5 points if it is a critical violation
- an additional 1.5 points if it is a repeat violation
- Finally 1/2 a point is added to the score if a violation is corrected during the inspection.

The total score for each vendor is made up of the scores for each of their three most recent inspections.
- 60% of the score comes from the most recent
- 30% of the score comes from the second most recent
- 10% of the score comes from the third most recent

**Comment by wbprice** [comment]
@ttavenner I think the database is missing a lot of scores.  Here's a screenshot: 
![screen shot 2014-08-31 at 4 21 26 pm](https://cloud.githubusercontent.com/assets/2590422/4103156/e2aaecd6-314c-11e4-8de8-0da0aed7dc5e.png)
In dev tools, the response from the API doesn't include the score.

**Comment by wbprice** [comment]
Changing siport mode deserves it's own issue, but the rest of this is finished.

**Comment by BretFisher** [comment]
I see lots of 100's, which I'm doubting. Do we have known issues or should we start flagging specific restaurants for a 2nd look in db/code. I'm happy to help with that work, just need some helpers on where to start.

**Comment by ttavenner** [comment]
I'm wondering if we should provide links directly to the Healthspace data (this is stored in the DB for quality checks and matching, just not exposed on the front end). This is what I do whenever I have a question. But the short answer to your question is that you can check the scores by just looking at the inspections in the app. They will get a 100 if they don't have any violations in a given inspection. Any violations at all should lower their score.

**Comment by kmcurry** [comment]
Given the explanation, the math for this Matsu does not compute or I still
don't understand:
http://openhealthinspection.com/#/vendor/matsu-sushi-japanese-restaurant-4392-holland-road-107

I think the 95 rating should be a 97:
100 start
-2 violation
-1.5 critical
+.5 fixed during

And then should the 100 overall go down a little?

On Wed, Sep 10, 2014 at 12:33 PM, Tommy Tavenner notifications@github.com
wrote:

> I'm wondering if we should provide links directly to the Healthspace data
> (this is stored in the DB for quality checks and matching, just not exposed
> on the front end). This is what I do whenever I have a question. But the
> short answer to your question is that you can check the scores by just
> looking at the inspections in the app. They will get a 100 if they don't
> have any violations in a given inspection. Any violations at all should
> lower their score.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/167#issuecomment-55143089
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by ttavenner** [comment]
The third inspection has 2 violations, so that would be:
-2 (x2) violation = -4 pts.
-1.5 (x1) critical = -1.5 pts.
+.5 (x1) fixed during inspection = +0.5

for a total of 5 pts. giving them a 95 for that inspection.

The weighting is 60%/30%/10%. which would be:
100pts x .6 = 60
100pts x .3 = 30
95pts x .1 = 9.5

for a total of 99.5. That is the score in the API, but I suspect some rounding is happening in the app.

**Comment by wbprice** [comment]
That's correct.  I should look at rounding down or adding at least two digits to the score displayed.

**Comment by ttavenner** [comment]
The api provides 1 decimal digit, so adding a digit would probably be the
way to go.

**Comment by BretFisher** [comment]
I’m getting feedback from friends (and myself) using this app that suggests
the scoring is too high or “forgiving”. For a restaurant to have multiple
major issues in multiple inspections and still grade a 90 may be an issue.
I would think most people associate a 90 as “great” (A-). Sorry I wasn’t
part of the “formula” conversation all along so I don’t know how we came to
the current one, and don’t want you to have to repeat anything here. The
other day I opened it and had a whole page full of 100’s. Do we have any
other state example that we’re basing it off of?  We don’t have to answer
here and can defer to hack night discussion. Eventually it would be optimal
to reference similar state formulas/systems do reduce liability and ensure
we’re as fair as we can be. It’s totally cool if we just started with a
simple formula and expected to enhance it over time… I just don’t have the
history on the topic yet.

**Comment by qwo** [comment]
@BretFisher this sounds like a good topic tonight. I think the simple scoring tommy uses is based off of similar criteria New York City uses.. (although i could be wrong).

I think the scoring is somewhat fair in respect to restaurant scores. I think its hard to think about it when we're talking about a 'score' out of 100.

Realistically a majority of restaurants should score between 60-100 with the majority scoring 80+. These restaurants are STILL operating, which means the Department of Health believes these are safe establishments still to operate. 

I feel like it is a lopsided curve, rather than a perfect bell curve distribution and it should be that way. 
Theres too many problem to solve if we started picking and dissecting or classifying these FDA codes. 

It should be graded like attendance :) and not like a math test.  We punish the players not playing by the rules but leave the C students alone :)
