### ISSUE TITLE
Google Maps Integration

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#21]
http://angular-google-maps.org/

**Comment by ttavenner** [comment]
Do you have an API key you are using for this? I'm testing some stuff on the Python side and it would make sense to use the same key throughout the app.

**Comment by wbprice** [comment]
Not yet. I've been working on getting the views up to snuff. If you get an API key for the Maps API, post it somewhere.

**Comment by ttavenner** [comment]
It looks like in V3, Google really split out their APIs. Now the key is connected to your personal Google account (like everything else in the universe) rather than a domain. Also, the Geocoding API is separate from the Maps Geolocation API, which in turn is separate from the Maps Javascript API. There are probably a half dozen other APIs. I turned on the Geocoding, which I want and the Geolocation and Javascript, which you probably want. I can either email you those keys or place them in a secure-ish location. That will probably give us what we need for testing but we might need something more sustainable long-term.

**Comment by ttavenner** [comment]
Better yet, you can organize your API access into projects, so I can just add you to the team in Google, if you've got an email address you'd like to use.

**Comment by wbprice** [comment]
Cool. I'm at 1wbprice@gmail.com.

**Comment by ttavenner** [comment]
I think with a little reconfiguring we can geocode restaurant addresses and store lat/long in the database as part of the ETL process. This should enable us to implement geolocation services such as "restaurants near me", etc with a much smaller number of Google API calls. We might even be able to offer these as a method of the API.
